=== YANG-DB/simpleschema/core/src/test/resources/json/schema/simpleNestedSchema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://opensearch.org/schemas/author",
  "additionalProperties": false,
  "title": "SimpleSample",
  "description": "An Author's book simple example",
  "type": "object",
  "required": [
    "id",
    "name",
    "born",
    "nationality"
  ],
  "properties": {
    "id": {
      "description": "The author's personal Id number",
      "type": "string"
    },
    "name": {
      "description": "The author's name",
      "type": "string"
    },
    "born": {
      "description": "The author's birth date",
      "type": "string",
      "format": "date"
    },
    "age": {
      "description": "The author's age",
      "type": "integer",
      "exclusiveMinimum": 0
    },
    "died": {
      "description": "The author's death date",
      "type": "string",
      "format": "date"
    },
    "nationality": {
      "description": "The author's nationality",
      "type": "string"
    },
    "books": {
      "description": "Books written by the author",
      "type": "array",
      "items": {
        "$ref": "/schemas/book"
      }
    }
  },
  "$defs": {
    "book": {
      "$id": "/schemas/book",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "ISBN",
        "title",
        "description",
        "published",
        "author"
      ],
      "properties": {
        "ISBN": {
          "description": "The Book's Id number",
          "type": "string"
        },
        "title": {
          "description": "The book's title",
          "type": "string"
        },
        "description": {
          "description": "The book's description",
          "type": "string"
        },
        "published": {
          "description": "The book's publishing date",
          "type": "string",
          "format": "date"
        },
        "genre": {
          "description": "The book's genre class",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "AdventureStories",
              "Classics",
              "Crime",
              "FairyTales",
              "Fantasy",
              "HistoricalFiction",
              "Horror",
              "Humour"
            ]
          }
        },
        "author": {
          "type": "object",
          "description": "The author's reference",
          "additionalProperties": false,
          "required": [
            "id"
          ],
          "properties": {
            "id": {
              "description": "The author's personal Id number",
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== YANG-DB/simpleschema/core/src/test/resources/json/validation/sampleValidData.json
{
  "id": "a1b2c3d4",
  "name": "J.K. Rowling",
  "born": "1965-11-30",
  "age" : 58,
  "nationality": "British",
  "books": [
    {
      "ISBN": "9781408855652",
      "title": "Harry Potter and the Philosopher's Stone",
      "description": "The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school and with the help of his friends, Ron Weasley and Hermione Granger, he faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.",
      "published": "1997-06-26",
      "genre": ["Fantasy"],
      "author": {
        "id": "a1b2c3d4"
      }
    },
    {
      "ISBN": "9788869185182",
      "title": "Harry Potter and the Chamber of Secrets",
      "description": " The plot follows Harry's second year at Hogwarts School of Witchcraft and Wizardry, during which a series of messages on the walls of the school's corridors warn that the \"Chamber of Secrets\" has been opened and that the \"heir of Slytherin\" would kill all pupils who do not come from all-magical families. These threats are found after attacks that leave residents of the school petrified. Throughout the year, Harry and his friends Ron and Hermione investigate the attacks.",
      "published": "1998-02-07",
      "genre": ["Fantasy"],
      "author": {
        "id": "a1b2c3d4"
      }
    }
  ]
}
